name: Astro Build and Test

on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ '*' ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build-and-test:
    name: Build and Test Astro Project
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.2.9'
          cache: true

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bunx vitest run

      - name: Build Astro project
        run: bunx astro build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: astro-build
          path: dist/
          retention-days: 7
